ROOT: data/raw
LOSS: Focal
MODEL: EfficientNet
TASK: Classify
INCLUDE_NORMAL: True
SPLIT_RATIO: 0.75:0.20:0.05
ATTENTION: True
USE_MASK: False
EP: 20
BATCH_SIZE: 32
PRETRAINED: True
SEED: 42
LR: 0.001
TO: cpu
PREP: True
