ROOT: data/raw
LOSS: Focal
MODEL: FPCN
TASK: Classify
INCLUDE_NORMAL: True
SPLIT_RATIO: 0.75:0.20:0.05
ATTENTION: True
USE_MASK: False
EP: 20
BATCH_SIZE: 32
PRETRAINED: True
SEED: 42
LR: 0.01
TO: cuda
PREP: True
