ROOT: data/raw
LOSS: CrossEntropy
MODEL: Unet
TASK: Segment
INCLUDE_NORMAL: False
SPLIT_RATIO: 0.75:0.20:0.05
EP: 20
BATCH_SIZE: 32
PRETRAINED: True
BACKBONE: resnet50
SEED: 42
LR: 0.01
TO: cpu
PREP: True
